name: malicious_sanity_checks

# execute this workflow automatically on all pushes and PRs
on: [push, pull_request]

jobs:

  unicode_warn:

    runs-on: ubuntu-latest
    container: debian:bullseye-slim

    steps:

    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash

    # TODO: test if this works for multiple commits pushed all at-once
    - name: Check diff for unicode
      run: |
        # TODO: actually grep this for unicode
        set -x
        git diff HEAD^
        echo "================================================================"
        git rev-parse origin
        git rev-parse origin/main
        git rev-parse origin/master
        git diff-tree -r `git rev-parse origin`
        git diff-tree -r `git rev-parse origin/main`
        git diff-tree -r `git rev-parse origin/master`
      shell: bash
