name: malicious_sanity_checks

# execute this workflow automatically on all pushes and PRs
on: [push, pull_request]

jobs:

  unicode_warn:

    runs-on: ubuntu-latest
    container: debian:bullseye-slim

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash

    # TODO: test if this works for multiple commits pushed all at-once
    - name: Check diff for unicode
      run: |
        set -x
        diff=`git diff ${{ github.event.before }}`
        echo ${diff} | grep -oP "[^\x00-\x7F]*"
        if [[ $? ]]; then
          echo "^^ WARNING: Unicode characters found in diff!"
          echo ${diff}
        else
          echo "INFO: No unicode characters found in push's commits"
        fi
      shell: bash
